# 32-bit Ubuntu with CS:APP tools + git
FROM i386/ubuntu:20.04

RUN apt update && \
    apt install -y \
      build-essential \
      gcc-multilib \
      git \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /work
